project_identifier: babel-plugin-handbook
api_key_env: CROWDIN_API_KEY
base_path: .
files:
  - source: '/README.md'
    translation: '/translations/%two_letters_code%/%original_file_name%'
    languages_mapping:
      two_letters_code:
        'de': 'de'
        'es-ES': 'es-ES'
        'fr': 'fr'
        'it': 'it'
        'ja': 'ja'
        'ko': 'ko'
        'nl': 'nl'
        'pt-PT': 'pt-PT'
        'ru': 'ru'
        'zh-CN': 'zh-CN'
