project_identifier: babel-plugin-handbook
api_key_env: CROWDIN_API_KEY
base_path: .
files:
  - source: '/README.md'
    translation: '/translations/%two_letters_code%/%original_file_name%'
    languages_mapping:
      two_letters_code:
        'af': 'af'
        'ar': 'ar'
        'ca': 'ca'
        'cs': 'cs'
        'da': 'da'
        'de': 'de'
        'el': 'el'
        'es-ES': 'es-ES'
        'fi': 'fi'
        'fr': 'fr'
        'he': 'he'
        'hu': 'hu'
        'it': 'it'
        'ja': 'ja'
        'ko': 'ko'
        'no': 'no'
        'nl': 'nl'
        'pl': 'pl'
        'pt-BR': 'pt-BR'
        'pt-PT': 'pt-PT'
        'ro': 'ro'
        'ru': 'ru'
        'sr': 'sr'
        'sv-SE': 'sv-SE'
        'tr': 'tr'
        'uk': 'uk'
        'vi': 'vi'
        'zh-CN': 'zh-CN'
        'zh-TW': 'zh-TW'
